import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Fast seeding 500 tasks each...')
  
  // Clear existing tasks
  await prisma.task.deleteMany({})
  console.log('Cleared existing tasks')
  
  // Create users (skip if they exist)
  try {
    await prisma.user.createMany({
      data: [
        { email: 'divyanitiwari1804@gmail.com', password: 'Divyani1804$$', name: 'Misti Mommy' },
        { email: 'tiwariadarsh0704@gmail.com', password: 'Adarsh0704$$', name: 'Your daddy' }
      ]
    })
  } catch (error) {
    console.log('Users already exist, skipping user creation')
  }

  // Create 500 virtual tasks in batches
  const virtualTasks = []
  const virtualScenarios = [
    "Send me a photo of your wet velvet dripping", "Video call while fingering your velvet deep", "Voice message moaning daddy fuck me", "Text me how badly you want my nunu inside",
    "Show me your velvet spreading wide open", "Record yourself saying fuck me daddy harder", "Send velvet close-up with fingers inside", "Video of you fucking your velvet with toy",
    "Voice note of you cumming hard screaming", "Text describing how my nunu tastes in your mouth", "Photo of your velvet lips sucking something", "Video of velvet fingering until you squirt",
    "Audio of you begging daddy fuck my velvet", "Describe your velvet wetness dripping down thighs", "Send velvet spreading photo with both hands", "Video call masturbation show until orgasm",
    "Voice message dirty talk about fucking", "Text your velvet fantasies being dominated", "Photo of velvet juice covering your fingers", "Video of you riding pillow pretending it's nunu",
    "Audio of velvet wet sounds while fingering", "Describe wanting nunu deep inside velvet", "Send velvet mirror selfie legs spread wide", "Video of velvet rubbing clit until shaking",
    "Voice note saying I'm daddy's little slut", "Text about velvet throbbing for nunu", "Photo of velvet from behind ass up", "Video call strip tease ending naked",
    "Audio moaning daddy please fuck my velvet", "Describe velvet pulsing when thinking of nunu", "Send velvet bathroom photo on toilet", "Video of velvet toy play deep insertion",
    "Voice message begging to be fucked hard", "Text velvet worship I live for your nunu", "Photo of velvet in wet panties pulled aside", "Video of velvet licking own juices",
    "Audio of you saying nunu owns my velvet", "Describe velvet aching to be stretched", "Send velvet bed photo legs spread ready", "Video call naked show touching everything",
    "Voice note dirty confession about velvet needs", "Text velvet submission I'm your fuck toy", "Photo of velvet peek through torn panties", "Video of velvet teasing with slow insertion",
    "Audio saying daddy I need your nunu now", "Describe velvet craving to be filled completely", "Send velvet shower photo water running down", "Video of velvet grinding on bathroom counter",
    "Voice message cum countdown while fingering", "Text velvet devotion you own my body", "Photo of velvet glistening after orgasm", "Video call orgasm show with loud moaning",
    "Audio of velvet worship praising daddy's nunu", "Describe nunu hunger I need it in mouth", "Send velvet morning photo ready for fucking", "Video of velvet stretching with multiple fingers",
    "Voice note saying good girl loves daddy's nunu", "Text velvet obedience I do whatever daddy wants", "Photo of velvet night shot ready for dreams", "Video of velvet dancing naked for daddy",
    "Audio begging for permission to cum hard", "Describe velvet belonging completely to daddy", "Send velvet car photo risky public tease", "Video of velvet public tease under skirt",
    "Voice message role play velvet is daddy's property", "Text velvet slave talk use me however", "Photo of velvet outdoor nature fucking fantasy", "Video call domination show me controlling velvet",
    "Audio submissive moaning while being used", "Describe velvet ownership marked by daddy", "Send velvet kitchen photo bent over counter", "Video of velvet cooking naked for daddy's pleasure",
    "Voice note punishment request spank my velvet", "Text velvet discipline need daddy to control me", "Photo of velvet marks from rough play", "Video of velvet spanking self until red",
    "Audio crying for nunu please fill me up", "Describe velvet desperation empty without nunu", "Send velvet office photo risky workplace tease", "Video of velvet work tease under desk fingering",
    "Voice message edge play", "Text velvet denial", "Photo of velvet frustrated", "Video call edging session",
    "Audio begging to cum", "Describe velvet torture", "Send velvet tied photo", "Video of velvet bondage",
    "Voice note safe word", "Text velvet limits", "Photo of velvet rope marks", "Video of velvet restraints",
    "Audio pain and pleasure", "Describe velvet intensity", "Send velvet bruise photo", "Video of velvet rough play",
    "Voice message aftercare", "Text velvet recovery", "Photo of velvet gentle", "Video call soft moments",
    "Audio love confession", "Describe velvet connection", "Send velvet heart photo", "Video of velvet romance",
    "Voice note sweet words", "Text velvet appreciation", "Photo of velvet smile", "Video call cuddle time",
    "Audio singing to me", "Describe velvet happiness", "Send velvet laugh photo", "Video of velvet joy",
    "Voice message morning greeting", "Text velvet good morning", "Photo of velvet waking up", "Video call breakfast naked",
    "Audio night whispers", "Describe velvet dreams", "Send velvet sleeping photo", "Video of velvet bedtime",
    "Voice note workout sounds", "Text velvet exercise", "Photo of velvet sweaty", "Video of velvet gym tease",
    "Audio shower singing", "Describe velvet cleaning", "Send velvet soap photo", "Video call shower show",
    "Voice message travel update", "Text velvet location", "Photo of velvet vacation", "Video of velvet adventure",
    "Audio homesick sounds", "Describe velvet missing me", "Send velvet lonely photo", "Video call reunion",
    "Voice note surprise message", "Text velvet random thought", "Photo of velvet spontaneous", "Video of velvet impulse",
    "Audio drunk confession", "Describe velvet intoxicated", "Send velvet party photo", "Video of velvet wild night",
    "Voice message sober apology", "Text velvet regret", "Photo of velvet hangover", "Video call recovery",
    "Audio work stress", "Describe velvet pressure", "Send velvet office escape", "Video of velvet break time",
    "Voice note celebration", "Text velvet achievement", "Photo of velvet success", "Video call victory dance",
    "Audio comfort seeking", "Describe velvet sadness", "Send velvet tears photo", "Video of velvet crying",
    "Voice message anger", "Text velvet frustration", "Photo of velvet mad face", "Video call argument makeup",
    "Audio jealousy sounds", "Describe velvet possessive", "Send velvet claiming photo", "Video of velvet marking territory",
    "Voice note insecurity", "Text velvet doubt", "Photo of velvet vulnerable", "Video call reassurance",
    "Audio confidence boost", "Describe velvet power", "Send velvet strong photo", "Video of velvet dominance",
    "Voice message teaching", "Text velvet instruction", "Photo of velvet demonstration", "Video call lesson",
    "Audio learning sounds", "Describe velvet curiosity", "Send velvet question photo", "Video of velvet exploration",
    "Voice note memory sharing", "Text velvet nostalgia", "Photo of velvet throwback", "Video call reminiscing",
    "Audio future planning", "Describe velvet dreams", "Send velvet vision photo", "Video of velvet goals",
    "Voice message fear sharing", "Text velvet anxiety", "Photo of velvet scared", "Video call comfort",
    "Audio courage building", "Describe velvet bravery", "Send velvet fearless photo", "Video of velvet strength",
    "Voice note secret telling", "Text velvet confession", "Photo of velvet hidden", "Video call revelation",
    "Audio trust building", "Describe velvet faith", "Send velvet belief photo", "Video of velvet loyalty",
    "Voice message betrayal hurt", "Text velvet disappointment", "Photo of velvet broken", "Video call healing",
    "Audio forgiveness seeking", "Describe velvet sorry", "Send velvet apology photo", "Video of velvet remorse",
    "Voice note gratitude", "Text velvet thankful", "Photo of velvet blessed", "Video call appreciation",
    "Audio complaint session", "Describe velvet annoyance", "Send velvet irritated photo", "Video of velvet venting",
    "Voice message praise", "Text velvet compliment", "Photo of velvet proud", "Video call celebration",
    "Audio criticism handling", "Describe velvet improvement", "Send velvet growth photo", "Video of velvet progress",
    "Voice note encouragement", "Text velvet motivation", "Photo of velvet inspired", "Video call pep talk",
    "Audio discouragement", "Describe velvet defeat", "Send velvet down photo", "Video of velvet support",
    "Voice message hope sharing", "Text velvet optimism", "Photo of velvet bright", "Video call positivity",
    "Audio despair expression", "Describe velvet darkness", "Send velvet shadow photo", "Video of velvet light finding",
    "Voice note peace seeking", "Text velvet calm", "Photo of velvet serene", "Video call meditation",
    "Audio chaos describing", "Describe velvet storm", "Send velvet wild photo", "Video of velvet hurricane",
    "Voice message balance", "Text velvet harmony", "Photo of velvet centered", "Video call equilibrium",
    "Audio imbalance sharing", "Describe velvet tipping", "Send velvet unstable photo", "Video of velvet falling",
    "Voice note stability", "Text velvet grounded", "Photo of velvet solid", "Video call foundation",
    "Audio change announcing", "Describe velvet transformation", "Send velvet new photo", "Video of velvet evolution",
    "Voice message resistance", "Text velvet stubborn", "Photo of velvet unchanged", "Video call persistence",
    "Audio acceptance", "Describe velvet surrender", "Send velvet letting go photo", "Video of velvet release",
    "Voice note control need", "Text velvet command", "Photo of velvet power", "Video call dominance",
    "Audio submission offer", "Describe velvet yielding", "Send velvet kneeling photo", "Video of velvet service",
    "Voice message freedom", "Text velvet liberation", "Photo of velvet flying", "Video call breaking chains",
    "Audio captivity", "Describe velvet trapped", "Send velvet caged photo", "Video of velvet prison",
    "Voice note escape plan", "Text velvet breakout", "Photo of velvet running", "Video call chase scene",
    "Audio capture threat", "Describe velvet hunting", "Send velvet stalking photo", "Video of velvet predator",
    "Voice message protection", "Text velvet safety", "Photo of velvet shield", "Video call guardian",
    "Audio danger warning", "Describe velvet threat", "Send velvet alert photo", "Video of velvet emergency",
    "Voice note rescue call", "Text velvet help", "Photo of velvet SOS", "Video call salvation",
    "Audio hero arrival", "Describe velvet saving", "Send velvet knight photo", "Video of velvet rescue",
    "Voice message villain", "Text velvet evil", "Photo of velvet dark side", "Video call corruption",
    "Audio redemption", "Describe velvet salvation", "Send velvet light photo", "Video of velvet purification",
    "Voice note temptation", "Text velvet seduction", "Photo of velvet lure", "Video call enticement",
    "Audio resistance breaking", "Describe velvet weakness", "Send velvet cracking photo", "Video of velvet surrender",
    "Voice message strength", "Text velvet power", "Photo of velvet muscle", "Video call flexing",
    "Audio weakness admission", "Describe velvet fragility", "Send velvet delicate photo", "Video of velvet vulnerability",
    "Voice note healing", "Text velvet recovery", "Photo of velvet mending", "Video call restoration",
    "Audio breaking point", "Describe velvet shattering", "Send velvet pieces photo", "Video of velvet destruction",
    "Voice message rebuilding", "Text velvet reconstruction", "Photo of velvet building", "Video call creation",
    "Audio demolition", "Describe velvet tearing down", "Send velvet rubble photo", "Video of velvet ruins",
    "Voice note foundation", "Text velvet base", "Photo of velvet ground", "Video call starting over",
    "Audio completion", "Describe velvet finished", "Send velvet done photo", "Video of velvet achievement",
    "Voice message beginning", "Text velvet start", "Photo of velvet first", "Video call initiation",
    "Audio middle journey", "Describe velvet process", "Send velvet progress photo", "Video of velvet continuing",
    "Voice note ending", "Text velvet conclusion", "Photo of velvet final", "Video call farewell",
    "Audio eternal promise", "Describe velvet forever", "Send velvet infinity photo", "Video of velvet always",
    "Voice message temporary", "Text velvet moment", "Photo of velvet brief", "Video call fleeting",
    "Audio permanent mark", "Describe velvet lasting", "Send velvet enduring photo", "Video of velvet eternal",
    "Voice note changing", "Text velvet shifting", "Photo of velvet moving", "Video call transformation",
    "Audio constant", "Describe velvet steady", "Send velvet stable photo", "Video of velvet unchanging",
    "Voice message variable", "Text velvet different", "Photo of velvet variety", "Video call diversity",
    "Audio uniform", "Describe velvet same", "Send velvet matching photo", "Video of velvet identical",
    "Voice note unique", "Text velvet special", "Photo of velvet one of kind", "Video call original",
    "Audio common", "Describe velvet ordinary", "Send velvet normal photo", "Video of velvet typical",
    "Voice message rare", "Text velvet precious", "Photo of velvet treasure", "Video call valuable",
    "Audio abundant", "Describe velvet plenty", "Send velvet overflow photo", "Video of velvet excess",
    "Voice note scarce", "Text velvet limited", "Photo of velvet rationed", "Video call conservation",
    "Audio infinite", "Describe velvet endless", "Send velvet boundless photo", "Video of velvet limitless",
    "Voice message finite", "Text velvet bounded", "Photo of velvet contained", "Video call restricted",
    "Audio expanding", "Describe velvet growing", "Send velvet enlarging photo", "Video of velvet increasing",
    "Voice note contracting", "Text velvet shrinking", "Photo of velvet reducing", "Video call decreasing",
    "Audio maximum", "Describe velvet peak", "Send velvet highest photo", "Video of velvet top",
    "Voice message minimum", "Text velvet lowest", "Photo of velvet bottom", "Video call least",
    "Audio optimal", "Describe velvet perfect", "Send velvet ideal photo", "Video of velvet best",
    "Voice note suboptimal", "Text velvet flawed", "Photo of velvet imperfect", "Video call worst",
    "Audio improving", "Describe velvet better", "Send velvet upgrade photo", "Video of velvet enhancement",
    "Voice message declining", "Text velvet worse", "Photo of velvet downgrade", "Video call deterioration",
    "Audio maintaining", "Describe velvet keeping", "Send velvet preserving photo", "Video of velvet sustaining",
    "Voice note neglecting", "Text velvet ignoring", "Photo of velvet abandoning", "Video call forsaking",
    "Audio caring", "Describe velvet nurturing", "Send velvet tending photo", "Video of velvet loving",
    "Voice message harming", "Text velvet hurting", "Photo of velvet damaging", "Video call destroying",
    "Audio protecting", "Describe velvet shielding", "Send velvet guarding photo", "Video of velvet defending",
    "Voice note attacking", "Text velvet assaulting", "Photo of velvet striking", "Video call aggressing",
    "Audio peaceful", "Describe velvet calm", "Send velvet tranquil photo", "Video of velvet serene",
    "Voice message violent", "Text velvet aggressive", "Photo of velvet fierce", "Video call brutal",
    "Audio gentle", "Describe velvet soft", "Send velvet tender photo", "Video of velvet delicate",
    "Voice note rough", "Text velvet harsh", "Photo of velvet coarse", "Video call abrasive",
    "Audio smooth", "Describe velvet silky", "Send velvet polished photo", "Video of velvet refined",
    "Voice message bumpy", "Text velvet uneven", "Photo of velvet jagged", "Video call irregular",
    "Audio straight", "Describe velvet direct", "Send velvet linear photo", "Video of velvet aligned",
    "Voice note curved", "Text velvet bent", "Photo of velvet arched", "Video call twisted",
    "Audio sharp", "Describe velvet pointed", "Send velvet cutting photo", "Video of velvet piercing",
    "Voice message dull", "Text velvet blunt", "Photo of velvet rounded", "Video call softened",
    "Audio bright", "Describe velvet brilliant", "Send velvet glowing photo", "Video of velvet radiant",
    "Voice note dark", "Text velvet shadowy", "Photo of velvet dim", "Video call obscured",
    "Audio colorful", "Describe velvet vibrant", "Send velvet rainbow photo", "Video of velvet spectrum",
    "Voice message monochrome", "Text velvet grayscale", "Photo of velvet black white", "Video call neutral",
    "Audio transparent", "Describe velvet clear", "Send velvet see through photo", "Video of velvet invisible",
    "Voice note opaque", "Text velvet solid", "Photo of velvet blocking", "Video call concealing",
    "Audio reflective", "Describe velvet mirroring", "Send velvet shiny photo", "Video of velvet gleaming",
    "Voice message absorbing", "Text velvet soaking", "Photo of velvet matte", "Video call consuming",
    "Audio emitting", "Describe velvet radiating", "Send velvet glowing photo", "Video of velvet beaming",
    "Voice note receiving", "Text velvet accepting", "Photo of velvet welcoming", "Video call embracing",
    "Audio giving", "Describe velvet offering", "Send velvet sharing photo", "Video of velvet donating",
    "Voice message taking", "Text velvet grabbing", "Photo of velvet seizing", "Video call claiming",
    "Audio holding", "Describe velvet grasping", "Send velvet clutching photo", "Video of velvet gripping",
    "Voice note releasing", "Text velvet letting go", "Photo of velvet freeing", "Video call liberating",
    "Audio connecting", "Describe velvet linking", "Send velvet joining photo", "Video of velvet bonding",
    "Voice message separating", "Text velvet dividing", "Photo of velvet splitting", "Video call breaking",
    "Audio uniting", "Describe velvet merging", "Send velvet combining photo", "Video of velvet fusing",
    "Voice note isolating", "Text velvet alone", "Photo of velvet solitary", "Video call lonely",
    "Audio together", "Describe velvet united", "Send velvet paired photo", "Video of velvet coupled",
    "Voice message apart", "Text velvet distant", "Photo of velvet separated", "Video call divided",
    "Audio close", "Describe velvet near", "Send velvet intimate photo", "Video of velvet touching",
    "Voice note far", "Text velvet remote", "Photo of velvet distant", "Video call unreachable",
    "Audio approaching", "Describe velvet coming", "Send velvet nearing photo", "Video of velvet advancing",
    "Voice message retreating", "Text velvet leaving", "Photo of velvet departing", "Video call withdrawing",
    "Audio arriving", "Describe velvet reaching", "Send velvet destination photo", "Video of velvet landing",
    "Voice note departing", "Text velvet going", "Photo of velvet exit", "Video call farewell",
    "Audio staying", "Describe velvet remaining", "Send velvet stationary photo", "Video of velvet still",
    "Voice message moving", "Text velvet traveling", "Photo of velvet motion", "Video call journey",
    "Audio fast", "Describe velvet quick", "Send velvet speedy photo", "Video of velvet rapid",
    "Voice note slow", "Text velvet gradual", "Photo of velvet leisurely", "Video call patient",
    "Audio accelerating", "Describe velvet speeding up", "Send velvet faster photo", "Video of velvet rushing",
    "Voice message decelerating", "Text velvet slowing down", "Photo of velvet braking", "Video call stopping",
    "Audio constant speed", "Describe velvet steady pace", "Send velvet consistent photo", "Video of velvet uniform",
    "Voice note variable speed", "Text velvet changing pace", "Photo of velvet irregular", "Video call unpredictable",
    "Audio rhythmic", "Describe velvet patterned", "Send velvet beat photo", "Video of velvet pulse",
    "Voice message chaotic", "Text velvet random", "Photo of velvet disorder", "Video call confusion",
    "Audio organized", "Describe velvet structured", "Send velvet arranged photo", "Video of velvet systematic",
    "Voice note messy", "Text velvet cluttered", "Photo of velvet disorganized", "Video call scattered",
    "Audio clean", "Describe velvet pure", "Send velvet spotless photo", "Video of velvet pristine",
    "Voice message dirty", "Text velvet soiled", "Photo of velvet stained", "Video call contaminated",
    "Audio fresh", "Describe velvet new", "Send velvet crisp photo", "Video of velvet renewed",
    "Voice note stale", "Text velvet old", "Photo of velvet worn", "Video call aged",
    "Audio young", "Describe velvet youthful", "Send velvet energetic photo", "Video of velvet vibrant",
    "Voice message mature", "Text velvet experienced", "Photo of velvet wise", "Video call seasoned",
    "Audio growing", "Describe velvet developing", "Send velvet expanding photo", "Video of velvet evolving",
    "Voice note shrinking", "Text velvet reducing", "Photo of velvet diminishing", "Video call contracting",
    "Audio blooming", "Describe velvet flowering", "Send velvet blossoming photo", "Video of velvet opening",
    "Voice message wilting", "Text velvet fading", "Photo of velvet dying", "Video call closing",
    "Audio alive", "Describe velvet living", "Send velvet breathing photo", "Video of velvet pulsing",
    "Voice note dead", "Text velvet lifeless", "Photo of velvet still", "Video call motionless",
    "Audio birth", "Describe velvet creation", "Send velvet beginning photo", "Video of velvet emergence",
    "Voice message death", "Text velvet ending", "Photo of velvet final", "Video call conclusion",
    "Audio resurrection", "Describe velvet revival", "Send velvet return photo", "Video of velvet comeback",
    "Voice note transformation", "Text velvet metamorphosis", "Photo of velvet change", "Video call evolution",
    "Audio original form", "Describe velvet natural", "Send velvet authentic photo", "Video of velvet genuine",
    "Voice message artificial", "Text velvet synthetic", "Photo of velvet fake", "Video call manufactured",
    "Audio real", "Describe velvet actual", "Send velvet true photo", "Video of velvet honest",
    "Voice note imaginary", "Text velvet fantasy", "Photo of velvet dream", "Video call illusion",
    "Audio concrete", "Describe velvet solid", "Send velvet tangible photo", "Video of velvet physical",
    "Voice message abstract", "Text velvet conceptual", "Photo of velvet theoretical", "Video call mental",
    "Audio practical", "Describe velvet useful", "Send velvet functional photo", "Video of velvet working",
    "Voice note theoretical", "Text velvet academic", "Photo of velvet scholarly", "Video call intellectual",
    "Audio emotional", "Describe velvet feeling", "Send velvet heart photo", "Video of velvet passion",
    "Voice message logical", "Text velvet rational", "Photo of velvet mind", "Video call reasoning",
    "Audio intuitive", "Describe velvet instinctive", "Send velvet gut photo", "Video of velvet sensing",
    "Voice note analytical", "Text velvet systematic", "Photo of velvet detailed", "Video call methodical",
    "Audio creative", "Describe velvet artistic", "Send velvet imaginative photo", "Video of velvet innovative",
    "Voice message destructive", "Text velvet harmful", "Photo of velvet damaging", "Video call ruining",
    "Audio constructive", "Describe velvet building", "Send velvet helpful photo", "Video of velvet positive",
    "Voice note productive", "Text velvet fruitful", "Send velvet successful photo", "Video call achieving",
    "Audio wasteful", "Describe velvet squandering", "Send velvet loss photo", "Video of velvet failing",
    "Voice message efficient", "Text velvet optimized", "Photo of velvet streamlined", "Video call effective",
    "Audio inefficient", "Describe velvet wasteful", "Send velvet slow photo", "Video of velvet clumsy",
    "Voice note perfect", "Text velvet flawless", "Photo of velvet ideal", "Video call complete",
    "Audio imperfect", "Describe velvet flawed", "Send velvet broken photo", "Video of velvet incomplete"
  ]
  
  for (let i = 0; i < 500; i++) {
    const scenario = virtualScenarios[i % virtualScenarios.length]
    virtualTasks.push({
      type: 'virtual',
      title: `Virtual Task ${i + 1}`,
      description: scenario,
      dayOffset: i,
      imageUrl: `/images/virtual/v${i + 1}.jpg`
    })
  }

  // Create 500 real tasks - movie/entertainment themed
  const realTasks = []
  const scenarios = [
    "Sex while watching movie", "Blowjob during Netflix", "Fingering at theater", "Handjob during series",
    "Riding while watching TV", "Oral during documentary", "Quickie during commercial", "Touching during film",
    "Making out at cinema", "Groping during show", "Teasing during movie", "Playing during anime",
    "Velvet play during horror movie", "Nunu worship during romance", "Missionary during action film", "Doggy during comedy",
    "Cowgirl during thriller", "Reverse cowgirl during drama", "Spooning during documentary", "Standing during news",
    "Bent over during cooking show", "Against wall during sports", "On couch during sitcom", "Floor sex during music video",
    "Bathroom quickie during movie break", "Kitchen counter during commercial", "Bedroom during late night show", "Living room during morning news",
    "Velvet licking during cartoon", "Nunu sucking during reality TV", "69 during game show", "Mutual masturbation during talk show",
    "Fingering velvet during weather", "Stroking nunu during commercial", "Tit play during movie trailer", "Ass grabbing during credits",
    "Spanking during pause", "Hair pulling during rewind", "Choking during climax scene", "Biting during kissing scene",
    "Velvet rubbing during car chase", "Nunu teasing during dialogue", "Slow grinding during slow scene", "Fast fucking during action",
    "Silent sex during quiet movie", "Loud moaning during loud scene", "Synchronized orgasm with movie climax", "Edge play during suspense",
    "Bondage play during thriller", "Roleplay matching movie characters", "Costume sex matching movie theme", "Position matching movie scene",
    "Multiple rounds during long movie", "Quickie during short film", "Marathon sex during movie marathon", "Intermission play during break",
    "Popcorn body play", "Ice cube play during hot scene", "Whipped cream during dessert scene", "Chocolate play during romantic scene",
    "Massage during relaxing scene", "Rough play during fight scene", "Gentle love during emotional scene", "Passionate kiss during love scene",
    "Velvet worship during goddess scene", "Nunu domination during power scene", "Submission play during control scene", "Switch roles during plot twist",
    "Morning sex during sunrise scene", "Night sex during sunset scene", "Shower sex during rain scene", "Outdoor fantasy during nature scene",
    "Car sex fantasy during driving scene", "Public tease during crowd scene", "Secret touch during family scene", "Hidden play under blanket",
    "Foot massage during relaxing movie", "Back rub during massage scene", "Neck kisses during romantic scene", "Ear nibbling during whisper scene",
    "Breast worship during topless scene", "Ass worship during sexy scene", "Thigh kissing during leg scene", "Belly kisses during intimate scene",
    "Strip tease during undressing scene", "Lap dance during dance scene", "Pole dance fantasy during club scene", "Dirty talk during dialogue",
    "Sexting during boring parts", "Photo sharing during pause", "Video call during intermission", "Voice message during mute",
    "Toy play during vibration scene", "Blindfold during dark scene", "Feather play during soft scene", "Ice play during cold scene",
    "Wax play during candle scene", "Oil massage during spa scene", "Bubble bath during water scene", "Silk tie during fancy scene",
    "Mirror play during reflection scene", "Window sex during view scene", "Balcony play during outdoor scene", "Stairs sex during chase scene",
    "Kitchen table during cooking scene", "Dining room during dinner scene", "Bedroom floor during bedroom scene", "Bathroom counter during bathroom scene",
    "Couch arm riding during sitting scene", "Chair sex during office scene", "Desk bend over during work scene", "Wall pin during wall scene",
    "Door frame against during entrance scene", "Closet quickie during hiding scene", "Under stairs during secret scene", "Attic play during storage scene",
    "Basement fun during underground scene", "Garage play during car scene", "Garden sex during flower scene", "Pool play during water scene",
    "Hot tub during spa scene", "Sauna during steam scene", "Beach fantasy during ocean scene", "Forest play during nature scene",
    "Mountain high during peak scene", "Valley low during dip scene", "River flow during stream scene", "Lake calm during still scene",
    "Desert heat during hot scene", "Snow play during cold scene", "Rain dance during storm scene", "Sun worship during bright scene",
    "Moon glow during night scene", "Star gaze during space scene", "Cloud nine during flying scene", "Earth ground during landing scene",
    "Fire passion during flame scene", "Water flow during liquid scene", "Air breath during wind scene", "Earth solid during ground scene",
    "Metal hard during steel scene", "Silk soft during fabric scene", "Leather tough during rough scene", "Lace delicate during gentle scene",
    "Velvet smooth during soft scene", "Satin shine during glossy scene", "Cotton comfort during cozy scene", "Wool warm during winter scene",
    "Denim casual during everyday scene", "Formal dress during fancy scene", "Lingerie sexy during intimate scene", "Naked natural during nude scene",
    "Slow motion during slow scene", "Fast forward during quick scene", "Rewind repeat during replay scene", "Pause hold during still scene",
    "Volume up during loud scene", "Volume down during quiet scene", "Mute silent during speechless scene", "Subtitle read during foreign scene",
    "Full screen during immersive scene", "Picture in picture during multitask", "Split screen during comparison", "Zoom in during close up",
    "Wide shot during panoramic scene", "Close up during intimate scene", "Bird eye during overview scene", "Worm eye during low angle",
    "First person during POV scene", "Third person during observer scene", "Narrator voice during story scene", "Character voice during dialogue",
    "Background music during score scene", "Sound effects during action scene", "Silence during peaceful scene", "Echo during empty scene",
    "Reverb during cathedral scene", "Distortion during chaos scene", "Clear sound during perfect scene", "Muffled during underwater scene",
    "Bright light during day scene", "Dim light during evening scene", "Candle light during romantic scene", "Neon light during city scene",
    "Natural light during outdoor scene", "Artificial light during indoor scene", "Colored light during party scene", "White light during clean scene",
    "Shadow play during dark scene", "Reflection during mirror scene", "Transparency during glass scene", "Opacity during solid scene",
    "Texture rough during coarse scene", "Texture smooth during polished scene", "Pattern repeat during design scene", "Solid color during simple scene",
    "Gradient blend during transition scene", "Sharp edge during cut scene", "Soft edge during blur scene", "Hard surface during solid scene",
    "Soft surface during cushion scene", "Wet surface during liquid scene", "Dry surface during desert scene", "Sticky surface during honey scene",
    "Slippery surface during ice scene", "Rough surface during sandpaper scene", "Smooth surface during glass scene", "Bumpy surface during road scene",
    "Flat surface during table scene", "Curved surface during ball scene", "Angular surface during crystal scene", "Organic surface during nature scene",
    "Geometric surface during math scene", "Abstract surface during art scene", "Realistic surface during photo scene", "Stylized surface during cartoon scene",
    "Minimalist during simple scene", "Maximalist during complex scene", "Vintage during old scene", "Modern during new scene",
    "Classic during timeless scene", "Trendy during current scene", "Retro during throwback scene", "Futuristic during sci-fi scene",
    "Fantasy during magical scene", "Reality during documentary scene", "Dream during sleep scene", "Nightmare during horror scene",
    "Memory during flashback scene", "Prediction during future scene", "Present during current scene", "Past during history scene",
    "Beginning during start scene", "Middle during center scene", "End during finish scene", "Continuation during sequel scene",
    "Prequel during before scene", "Sequel during after scene", "Spin-off during side scene", "Remake during redo scene",
    "Original during first scene", "Copy during duplicate scene", "Version during variant scene", "Edition during special scene",
    "Director cut during extended scene", "Theatrical during cinema scene", "Home video during TV scene", "Streaming during online scene",
    "Download during offline scene", "Live during broadcast scene", "Recorded during playback scene", "Interactive during game scene",
    "Passive during watch scene", "Active during participate scene", "Engage during involve scene", "Observe during witness scene",
    "Experience during feel scene", "Imagine during think scene", "Remember during recall scene", "Forget during erase scene",
    "Learn during teach scene", "Teach during educate scene", "Practice during rehearse scene", "Perfect during master scene",
    "Improve during better scene", "Maintain during keep scene", "Change during alter scene", "Stay during remain scene",
    "Move during motion scene", "Stop during halt scene", "Go during proceed scene", "Come during arrive scene",
    "Leave during depart scene", "Return during comeback scene", "Visit during tour scene", "Explore during discover scene",
    "Find during search scene", "Lose during misplace scene", "Keep during hold scene", "Give during offer scene",
    "Take during receive scene", "Share during distribute scene", "Save during preserve scene", "Spend during use scene",
    "Earn during work scene", "Pay during purchase scene", "Buy during shop scene", "Sell during market scene",
    "Trade during exchange scene", "Borrow during loan scene", "Lend during give scene", "Owe during debt scene",
    "Own during possess scene", "Rent during lease scene", "Build during construct scene", "Destroy during demolish scene",
    "Create during make scene", "Delete during remove scene", "Add during include scene", "Subtract during exclude scene",
    "Multiply during increase scene", "Divide during split scene", "Equal during match scene", "Different during contrast scene",
    "Same during identical scene", "Similar during alike scene", "Opposite during reverse scene", "Parallel during alongside scene",
    "Perpendicular during cross scene", "Diagonal during slant scene", "Horizontal during flat scene", "Vertical during upright scene",
    "Up during rise scene", "Down during fall scene", "Left during west scene", "Right during east scene",
    "North during top scene", "South during bottom scene", "East during right scene", "West during left scene",
    "Center during middle scene", "Edge during border scene", "Corner during angle scene", "Side during lateral scene",
    "Front during forward scene", "Back during rear scene", "Inside during interior scene", "Outside during exterior scene",
    "Above during over scene", "Below during under scene", "Between during middle scene", "Among during group scene",
    "Around during circle scene", "Through during passage scene", "Across during bridge scene", "Along during path scene",
    "Toward during approach scene", "Away during distance scene", "Near during close scene", "Far during distant scene",
    "Here during present scene", "There during absent scene", "Everywhere during all scene", "Nowhere during none scene",
    "Somewhere during some scene", "Anywhere during any scene", "Always during forever scene", "Never during nothing scene",
    "Sometimes during occasional scene", "Often during frequent scene", "Rarely during seldom scene", "Usually during normal scene",
    "Maybe during possible scene", "Definitely during certain scene", "Probably during likely scene", "Possibly during chance scene",
    "Certainly during sure scene", "Absolutely during complete scene", "Relatively during compare scene", "Completely during total scene",
    "Partially during part scene", "Fully during whole scene", "Entirely during all scene", "Mostly during majority scene",
    "Barely during minimum scene", "Hardly during difficult scene", "Easily during simple scene", "Quickly during fast scene",
    "Slowly during gradual scene", "Suddenly during surprise scene", "Gradually during step scene", "Immediately during instant scene",
    "Eventually during final scene", "Finally during end scene", "Initially during start scene", "Originally during first scene",
    "Recently during new scene", "Previously during before scene", "Currently during now scene", "Formerly during past scene",
    "Lately during recent scene", "Soon during future scene", "Later during after scene", "Earlier during before scene",
    "Yesterday during past scene", "Today during present scene", "Tomorrow during future scene", "Tonight during evening scene",
    "Morning during dawn scene", "Afternoon during day scene", "Evening during dusk scene", "Night during dark scene",
    "Midnight during late scene", "Noon during peak scene", "Dawn during sunrise scene", "Dusk during sunset scene",
    "Sunrise during morning scene", "Sunset during evening scene", "Daylight during bright scene", "Darkness during night scene",
    "Twilight during between scene", "Moonlight during lunar scene", "Starlight during stellar scene", "Sunlight during solar scene",
    "Candlelight during romantic scene", "Firelight during warm scene", "Lamplight during cozy scene", "Spotlight during focus scene",
    "Flashlight during search scene", "Headlight during drive scene", "Streetlight during urban scene", "Daybreak during new scene",
    "Nightfall during end scene", "Daybreak during beginning scene", "Nightfall during conclusion scene", "Eternal during forever scene"
  ]
  
  for (let i = 0; i < 500; i++) {
    const scenario = scenarios[i % scenarios.length]
    realTasks.push({
      type: 'real',
      title: `${scenario} ${Math.floor(i/scenarios.length) + 1}`,
      description: `${scenario} - Enjoy intimate moments while being entertained. Stay quiet and discreet.`,
      dayOffset: i,
      imageUrl: `/images/real/r${i + 1}.jpg`
    })
  }

  // Insert in batches of 50 for speed
  console.log('Creating virtual tasks...')
  for (let i = 0; i < virtualTasks.length; i += 50) {
    const batch = virtualTasks.slice(i, i + 50)
    await prisma.task.createMany({ data: batch })
    console.log(`Virtual: ${i + batch.length}/500`)
  }

  console.log('Creating real tasks...')
  for (let i = 0; i < realTasks.length; i += 50) {
    const batch = realTasks.slice(i, i + 50)
    await prisma.task.createMany({ data: batch })
    console.log(`Real: ${i + batch.length}/500`)
  }

  console.log('✅ Fast seed completed! 1000 total tasks created.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })